import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-400 text-gray-900">
        <header className="w-full px-4 py-5 bg-black shadow-md z-index-5">
          <nav className="max-w-[1250px] mx-auto flex items-center justify-between">
            <div className="text-green-400 text-2xl font-bold">My Website</div>
            <div className="flex gap-6">
              <Link
                href="/"
                className="text-white text-lg font-medium hover:text-green-500 transition-all duration-300"
              >
                Home
              </Link>
              <Link
                href="/about"
                className="text-white text-lg font-medium hover:text-green-500 transition-all duration-300"
              >
                About
              </Link>
              <Link
                href="/contact"
                className="text-white text-lg font-medium hover:text-green-500 transition-all duration-300"
              >
                Contact
              </Link>
            </div>
          </nav>
        </header>
        <main className="w-full mx-auto mt-8">{children}</main>
       
      </body>
    </html>
  );
}
